# Generated by Django 3.1.4 on 2020-12-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_track', '0002_timelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='totalHours',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
